"""create metrics

Revision ID: 4993a0799f32
Revises: d969b9b1cdca
Create Date: 2026-06-27 20:58:57.193992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4993a0799f32'
down_revision: Union[str, Sequence[str], None] = 'd969b9b1cdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(op.f('companies_cik_key'), 'companies', type_='unique')
    #op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.add_column('metrics', sa.Column('metric_category', sa.String(length=100), nullable=True))
    op.add_column('metrics', sa.Column('numeric_value', sa.Double(), nullable=True))
    op.add_column('metrics', sa.Column('text_value', sa.Text(), nullable=True))
    op.add_column('metrics', sa.Column('boolean_value', sa.Boolean(), nullable=True))
    op.drop_column('metrics', 'metric_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('metrics', 'boolean_value')
    op.drop_column('metrics', 'text_value')
    op.drop_column('metrics', 'numeric_value')
    op.drop_column('metrics', 'metric_category')
    #op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    #op.create_unique_constraint(op.f('companies_cik_key'), 'companies', ['cik'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
