"""create filings

Revision ID: b724116f3ae4
Revises: f08c04d4f47b
Create Date: 2026-06-27 19:12:37.417851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b724116f3ae4'
down_revision: Union[str, Sequence[str], None] = 'f08c04d4f47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filer_type', sa.String(length=30), nullable=True),
    sa.Column('filing_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filing_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_cik'), 'filings', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_filing_time'), 'filings', ['filing_time'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_filings_filing_time'), table_name='filings')
    op.drop_index(op.f('ix_filings_cik'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
