"""create metrics

Revision ID: d969b9b1cdca
Revises: b724116f3ae4
Create Date: 2026-06-27 20:54:53.555424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd969b9b1cdca'
down_revision: Union[str, Sequence[str], None] = 'b724116f3ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_accession_number'), 'metrics', ['accession_number'], unique=False)
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    #op.drop_constraint(op.f('companies_cik_key'), 'companies', type_='unique')
    #op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    #op.create_unique_constraint(op.f('companies_cik_key'), 'companies', ['cik'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_accession_number'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
