"""add companies table

Revision ID: f08c04d4f47b
Revises: d4baee77442c
Create Date: 2026-06-27 11:52:50.296056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08c04d4f47b'
down_revision: Union[str, Sequence[str], None] = 'd4baee77442c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.drop_constraint(op.f('sessions_refresh_token_key'), 'sessions', type_='unique')
    op.drop_column('sessions', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('sessions_refresh_token_key'), 'sessions', ['refresh_token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
